version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    init: true
    working_dir: "/yanaken"
    volumes:
      - ./src:/yanaken
    ports:
      - "3000:3000"